<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bulk Salary Slips - {{ $month }}</title>
    <style>
        @page {
            margin: 15mm;
            size: A4;
        }
        
        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            line-height: 1.2;
            color: #333;
            margin: 0;
            padding: 0;
        }
        
        .cover-page {
            text-align: center;
            margin-top: 100px;
        }
        
        .cover-page h1 {
            font-size: 28px;
            color: #007bff;
            margin-bottom: 20px;
        }
        
        .cover-page h2 {
            font-size: 20px;
            color: #333;
            margin-bottom: 30px;
        }
        
        .cover-page p {
            font-size: 12px;
            color: #666;
            margin: 10px 0;
        }
        
        .salary-slip {
            page-break-after: always;
            margin-bottom: 20px;
        }
        
        .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 100px;
            color: #ccc;
            opacity: 0.1;
            z-index: -1;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="watermark">EDUNEXUS</div>
    
    <!-- Cover Page -->
    <div class="cover-page">
        <h1>EduNexus ERP + LMS</h1>
        <h2>Bulk Salary Slips</h2>
        <p><strong>Period:</strong> {{ $month }}</p>
        <p><strong>Generated on:</strong> {{ $generated_at }}</p>
        <p><strong>Generated by:</strong> {{ $generated_by }}</p>
        <p><strong>Total Salary Slips:</strong> {{ count($salarySlips) }}</p>
        <br><br><br>
        <p style="font-size: 10px; color: #999;">This document contains individual salary slips for all employees.</p>
    </div>
    
    <!-- Page Break -->
    <div style="page-break-before: always;"></div>
    
    <!-- Individual Salary Slips -->
    @foreach($salarySlips as $index => $salarySlip)
        <div class="salary-slip">
            {!! $salarySlip !!}
            
            @if($index < count($salarySlips) - 1)
                <div style="page-break-after: always;"></div>
            @endif
        </div>
    @endforeach
</body>
</html>
